<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends ReadOnlyBase
{
    //
    protected $countries = [ 
        ["name"=> "Afghanistan", "code"=> "AF"], 
        ["name"=> "Aland Islands", "code"=> "AX"], 
        ["name"=> "Albania", "code"=> "AL"], 
        ["name"=> "Algeria", "code"=> "DZ"], 
        ["name"=> "American Samoa", "code"=> "AS"], 
        ["name"=> "AndorrA", "code"=> "AD"], 
        ["name"=> "Angola", "code"=> "AO"], 
        ["name"=> "Anguilla", "code"=> "AI"], 
        ["name"=> "Antarctica", "code"=> "AQ"], 
        ["name"=> "Antigua and Barbuda", "code"=> "AG"], 
        ["name"=> "Argentina", "code"=> "AR"], 
        ["name"=> "Armenia", "code"=> "AM"], 
        ["name"=> "Aruba", "code"=> "AW"], 
        ["name"=> "Australia", "code"=> "AU"], 
        ["name"=> "Austria", "code"=> "AT"], 
        ["name"=> "Azerbaijan", "code"=> "AZ"], 
        ["name"=> "Bahamas", "code"=> "BS"], 
        ["name"=> "Bahrain", "code"=> "BH"], 
        ["name"=> "Bangladesh", "code"=> "BD"], 
        ["name"=> "Barbados", "code"=> "BB"], 
        ["name"=> "Belarus", "code"=> "BY"], 
        ["name"=> "Belgium", "code"=> "BE"], 
        ["name"=> "Belize", "code"=> "BZ"], 
        ["name"=> "Benin", "code"=> "BJ"], 
        ["name"=> "Bermuda", "code"=> "BM"], 
        ["name"=> "Bhutan", "code"=> "BT"], 
        ["name"=> "Bolivia", "code"=> "BO"], 
        ["name"=> "Bosnia and Herzegovina", "code"=> "BA"], 
        ["name"=> "Botswana", "code"=> "BW"], 
        ["name"=> "Bouvet Island", "code"=> "BV"], 
        ["name"=> "Brazil", "code"=> "BR"], 
        ["name"=> "British Indian Ocean Territory", "code"=> "IO"], 
        ["name"=> "Brunei Darussalam", "code"=> "BN"], 
        ["name"=> "Bulgaria", "code"=> "BG"], 
        ["name"=> "Burkina Faso", "code"=> "BF"], 
        ["name"=> "Burundi", "code"=> "BI"], 
        ["name"=> "Cambodia", "code"=> "KH"], 
        ["name"=> "Cameroon", "code"=> "CM"], 
        ["name"=> "Canada", "code"=> "CA"], 
        ["name"=> "Cape Verde", "code"=> "CV"], 
        ["name"=> "Cayman Islands", "code"=> "KY"], 
        ["name"=> "Central African Republic", "code"=> "CF"], 
        ["name"=> "Chad", "code"=> "TD"], 
        ["name"=> "Chile", "code"=> "CL"], 
        ["name"=> "China", "code"=> "CN"], 
        ["name"=> "Christmas Island", "code"=> "CX"], 
        ["name"=> "Cocos (Keeling) Islands", "code"=> "CC"], 
        ["name"=> "Colombia", "code"=> "CO"], 
        ["name"=> "Comoros", "code"=> "KM"], 
        ["name"=> "Congo", "code"=> "CG"], 
        ["name"=> "Congo, The Democratic Republic of the", "code"=> "CD"], 
        ["name"=> "Cook Islands", "code"=> "CK"], 
        ["name"=> "Costa Rica", "code"=> "CR"], 
        ["name"=> "Cote D'Ivoire", "code"=> "CI"], 
        ["name"=> "Croatia", "code"=> "HR"], 
        ["name"=> "Cuba", "code"=> "CU"], 
        ["name"=> "Cyprus", "code"=> "CY"], 
        ["name"=> "Czech Republic", "code"=> "CZ"], 
        ["name"=> "Denmark", "code"=> "DK"], 
        ["name"=> "Djibouti", "code"=> "DJ"], 
        ["name"=> "Dominica", "code"=> "DM"], 
        ["name"=> "Dominican Republic", "code"=> "DO"], 
        ["name"=> "Ecuador", "code"=> "EC"], 
        ["name"=> "Egypt", "code"=> "EG"], 
        ["name"=> "El Salvador", "code"=> "SV"], 
        ["name"=> "Equatorial Guinea", "code"=> "GQ"], 
        ["name"=> "Eritrea", "code"=> "ER"], 
        ["name"=> "Estonia", "code"=> "EE"], 
        ["name"=> "Ethiopia", "code"=> "ET"], 
        ["name"=> "Falkland Islands (Malvinas)", "code"=> "FK"], 
        ["name"=> "Faroe Islands", "code"=> "FO"], 
        ["name"=> "Fiji", "code"=> "FJ"], 
        ["name"=> "Finland", "code"=> "FI"], 
        ["name"=> "France", "code"=> "FR"], 
        ["name"=> "French Guiana", "code"=> "GF"], 
        ["name"=> "French Polynesia", "code"=> "PF"], 
        ["name"=> "French Southern Territories", "code"=> "TF"], 
        ["name"=> "Gabon", "code"=> "GA"], 
        ["name"=> "Gambia", "code"=> "GM"], 
        ["name"=> "Georgia", "code"=> "GE"], 
        ["name"=> "Germany", "code"=> "DE"], 
        ["name"=> "Ghana", "code"=> "GH"], 
        ["name"=> "Gibraltar", "code"=> "GI"], 
        ["name"=> "Greece", "code"=> "GR"], 
        ["name"=> "Greenland", "code"=> "GL"], 
        ["name"=> "Grenada", "code"=> "GD"], 
        ["name"=> "Guadeloupe", "code"=> "GP"], 
        ["name"=> "Guam", "code"=> "GU"], 
        ["name"=> "Guatemala", "code"=> "GT"], 
        ["name"=> "Guernsey", "code"=> "GG"], 
        ["name"=> "Guinea", "code"=> "GN"], 
        ["name"=> "Guinea-Bissau", "code"=> "GW"], 
        ["name"=> "Guyana", "code"=> "GY"], 
        ["name"=> "Haiti", "code"=> "HT"], 
        ["name"=> "Heard Island and Mcdonald Islands", "code"=> "HM"], 
        ["name"=> "Holy See (Vatican City State)", "code"=> "VA"], 
        ["name"=> "Honduras", "code"=> "HN"], 
        ["name"=> "Hong Kong", "code"=> "HK"], 
        ["name"=> "Hungary", "code"=> "HU"], 
        ["name"=> "Iceland", "code"=> "IS"], 
        ["name"=> "India", "code"=> "IN"], 
        ["name"=> "Indonesia", "code"=> "ID"], 
        ["name"=> "Iran, Islamic Republic Of", "code"=> "IR"], 
        ["name"=> "Iraq", "code"=> "IQ"], 
        ["name"=> "Ireland", "code"=> "IE"], 
        ["name"=> "Isle of Man", "code"=> "IM"], 
        ["name"=> "Israel", "code"=> "IL"], 
        ["name"=> "Italy", "code"=> "IT"], 
        ["name"=> "Jamaica", "code"=> "JM"], 
        ["name"=> "Japan", "code"=> "JP"], 
        ["name"=> "Jersey", "code"=> "JE"], 
        ["name"=> "Jordan", "code"=> "JO"], 
        ["name"=> "Kazakhstan", "code"=> "KZ"], 
        ["name"=> "Kenya", "code"=> "KE"], 
        ["name"=> "Kiribati", "code"=> "KI"], 
        ["name"=> "Korea, Democratic People's Republic of", "code"=> "KP"], 
        ["name"=> "Korea, Republic of", "code"=> "KR"], 
        ["name"=> "Kuwait", "code"=> "KW"], 
        ["name"=> "Kyrgyzstan", "code"=> "KG"], 
        ["name"=> "Lao People's Democratic Republic", "code"=> "LA"], 
        ["name"=> "Latvia", "code"=> "LV"], 
        ["name"=> "Lebanon", "code"=> "LB"], 
        ["name"=> "Lesotho", "code"=> "LS"], 
        ["name"=> "Liberia", "code"=> "LR"], 
        ["name"=> "Libyan Arab Jamahiriya", "code"=> "LY"], 
        ["name"=> "Liechtenstein", "code"=> "LI"], 
        ["name"=> "Lithuania", "code"=> "LT"], 
        ["name"=> "Luxembourg", "code"=> "LU"], 
        ["name"=> "Macao", "code"=> "MO"], 
        ["name"=> "Macedonia, The Former Yugoslav Republic of", "code"=> "MK"], 
        ["name"=> "Madagascar", "code"=> "MG"], 
        ["name"=> "Malawi", "code"=> "MW"], 
        ["name"=> "Malaysia", "code"=> "MY"], 
        ["name"=> "Maldives", "code"=> "MV"], 
        ["name"=> "Mali", "code"=> "ML"], 
        ["name"=> "Malta", "code"=> "MT"], 
        ["name"=> "Marshall Islands", "code"=> "MH"], 
        ["name"=> "Martinique", "code"=> "MQ"], 
        ["name"=> "Mauritania", "code"=> "MR"], 
        ["name"=> "Mauritius", "code"=> "MU"], 
        ["name"=> "Mayotte", "code"=> "YT"], 
        ["name"=> "Mexico", "code"=> "MX"], 
        ["name"=> "Micronesia, Federated States of", "code"=> "FM"], 
        ["name"=> "Moldova, Republic of", "code"=> "MD"], 
        ["name"=> "Monaco", "code"=> "MC"], 
        ["name"=> "Mongolia", "code"=> "MN"], 
        ["name"=> "Montenegro", "code"=> "ME"],
        ["name"=> "Montserrat", "code"=> "MS"],
        ["name"=> "Morocco", "code"=> "MA"], 
        ["name"=> "Mozambique", "code"=> "MZ"], 
        ["name"=> "Myanmar", "code"=> "MM"], 
        ["name"=> "Namibia", "code"=> "NA"], 
        ["name"=> "Nauru", "code"=> "NR"], 
        ["name"=> "Nepal", "code"=> "NP"], 
        ["name"=> "Netherlands", "code"=> "NL"], 
        ["name"=> "Netherlands Antilles", "code"=> "AN"], 
        ["name"=> "New Caledonia", "code"=> "NC"], 
        ["name"=> "New Zealand", "code"=> "NZ"], 
        ["name"=> "Nicaragua", "code"=> "NI"], 
        ["name"=> "Niger", "code"=> "NE"], 
        ["name"=> "Nigeria", "code"=> "NG"], 
        ["name"=> "Niue", "code"=> "NU"], 
        ["name"=> "Norfolk Island", "code"=> "NF"], 
        ["name"=> "Northern Mariana Islands", "code"=> "MP"], 
        ["name"=> "Norway", "code"=> "NO"], 
        ["name"=> "Oman", "code"=> "OM"], 
        ["name"=> "Pakistan", "code"=> "PK"], 
        ["name"=> "Palau", "code"=> "PW"], 
        ["name"=> "Palestinian Territory, Occupied", "code"=> "PS"], 
        ["name"=> "Panama", "code"=> "PA"], 
        ["name"=> "Papua New Guinea", "code"=> "PG"], 
        ["name"=> "Paraguay", "code"=> "PY"], 
        ["name"=> "Peru", "code"=> "PE"], 
        ["name"=> "Philippines", "code"=> "PH"], 
        ["name"=> "Pitcairn", "code"=> "PN"], 
        ["name"=> "Poland", "code"=> "PL"], 
        ["name"=> "Portugal", "code"=> "PT"], 
        ["name"=> "Puerto Rico", "code"=> "PR"], 
        ["name"=> "Qatar", "code"=> "QA"], 
        ["name"=> "Reunion", "code"=> "RE"], 
        ["name"=> "Romania", "code"=> "RO"], 
        ["name"=> "Russian Federation", "code"=> "RU"], 
        ["name"=> "RWANDA", "code"=> "RW"], 
        ["name"=> "Saint Helena", "code"=> "SH"], 
        ["name"=> "Saint Kitts and Nevis", "code"=> "KN"], 
        ["name"=> "Saint Lucia", "code"=> "LC"], 
        ["name"=> "Saint Pierre and Miquelon", "code"=> "PM"], 
        ["name"=> "Saint Vincent and the Grenadines", "code"=> "VC"], 
        ["name"=> "Samoa", "code"=> "WS"], 
        ["name"=> "San Marino", "code"=> "SM"], 
        ["name"=> "Sao Tome and Principe", "code"=> "ST"], 
        ["name"=> "Saudi Arabia", "code"=> "SA"], 
        ["name"=> "Senegal", "code"=> "SN"], 
        ["name"=> "Serbia", "code"=> "RS"], 
        ["name"=> "Seychelles", "code"=> "SC"], 
        ["name"=> "Sierra Leone", "code"=> "SL"], 
        ["name"=> "Singapore", "code"=> "SG"], 
        ["name"=> "Slovakia", "code"=> "SK"], 
        ["name"=> "Slovenia", "code"=> "SI"], 
        ["name"=> "Solomon Islands", "code"=> "SB"], 
        ["name"=> "Somalia", "code"=> "SO"], 
        ["name"=> "South Africa", "code"=> "ZA"], 
        ["name"=> "South Georgia and the South Sandwich Islands", "code"=> "GS"], 
        ["name"=> "Spain", "code"=> "ES"], 
        ["name"=> "Sri Lanka", "code"=> "LK"], 
        ["name"=> "Sudan", "code"=> "SD"], 
        ["name"=> "Suriname", "code"=> "SR"], 
        ["name"=> "Svalbard and Jan Mayen", "code"=> "SJ"], 
        ["name"=> "Swaziland", "code"=> "SZ"], 
        ["name"=> "Sweden", "code"=> "SE"], 
        ["name"=> "Switzerland", "code"=> "CH"], 
        ["name"=> "Syrian Arab Republic", "code"=> "SY"], 
        ["name"=> "Taiwan, Province of China", "code"=> "TW"], 
        ["name"=> "Tajikistan", "code"=> "TJ"], 
        ["name"=> "Tanzania, United Republic of", "code"=> "TZ"], 
        ["name"=> "Thailand", "code"=> "TH"], 
        ["name"=> "Timor-Leste", "code"=> "TL"], 
        ["name"=> "Togo", "code"=> "TG"], 
        ["name"=> "Tokelau", "code"=> "TK"], 
        ["name"=> "Tonga", "code"=> "TO"], 
        ["name"=> "Trinidad and Tobago", "code"=> "TT"], 
        ["name"=> "Tunisia", "code"=> "TN"], 
        ["name"=> "Turkey", "code"=> "TR"], 
        ["name"=> "Turkmenistan", "code"=> "TM"], 
        ["name"=> "Turks and Caicos Islands", "code"=> "TC"], 
        ["name"=> "Tuvalu", "code"=> "TV"], 
        ["name"=> "Uganda", "code"=> "UG"], 
        ["name"=> "Ukraine", "code"=> "UA"], 
        ["name"=> "United Arab Emirates", "code"=> "AE"], 
        ["name"=> "United Kingdom", "code"=> "GB"], 
        ["name"=> "United States", "code"=> "US"], 
        ["name"=> "United States Minor Outlying Islands", "code"=> "UM"], 
        ["name"=> "Uruguay", "code"=> "UY"], 
        ["name"=> "Uzbekistan", "code"=> "UZ"], 
        ["name"=> "Vanuatu", "code"=> "VU"], 
        ["name"=> "Venezuela", "code"=> "VE"], 
        ["name"=> "Viet Nam", "code"=> "VN"], 
        ["name"=> "Virgin Islands, British", "code"=> "VG"], 
        ["name"=> "Virgin Islands, U.S.", "code"=> "VI"], 
        ["name"=> "Wallis and Futuna", "code"=> "WF"], 
        ["name"=> "Western Sahara", "code"=> "EH"], 
        ["name"=> "Yemen", "code"=> "YE"], 
        ["name"=> "Zambia", "code"=> "ZM"], 
        ["name"=> "Zimbabwe", "code"=> "ZW"] 
    ];

    protected $timezones = [
        'name' => 'America/Adak' => '(GMT-10:00) America/Adak (Hawaii-Aleutian Standard Time)',
        'name' =>'America/Atka' => '(GMT-10:00) America/Atka (Hawaii-Aleutian Standard Time)',
        'name' =>'America/Anchorage' => '(GMT-9:00) America/Anchorage (Alaska Standard Time)',
        'name' =>'America/Juneau' => '(GMT-9:00) America/Juneau (Alaska Standard Time)',
        'name' =>'America/Nome' => '(GMT-9:00) America/Nome (Alaska Standard Time)',
        'name' =>'America/Yakutat' => '(GMT-9:00) America/Yakutat (Alaska Standard Time)',
        'name' =>'America/Dawson' => '(GMT-8:00) America/Dawson (Pacific Standard Time)',
        'name' =>'America/Ensenada' => '(GMT-8:00) America/Ensenada (Pacific Standard Time)',
        'name' =>'America/Los_Angeles' => '(GMT-8:00) America/Los_Angeles (Pacific Standard Time)',
        'name' =>'America/Tijuana' => '(GMT-8:00) America/Tijuana (Pacific Standard Time)',
        'name' =>'America/Vancouver' => '(GMT-8:00) America/Vancouver (Pacific Standard Time)',
        'name' =>'America/Whitehorse' => '(GMT-8:00) America/Whitehorse (Pacific Standard Time)',
        'name' =>'Canada/Pacific' => '(GMT-8:00) Canada/Pacific (Pacific Standard Time)',
        'name' =>'Canada/Yukon' => '(GMT-8:00) Canada/Yukon (Pacific Standard Time)',
        'name' =>'Mexico/BajaNorte' => '(GMT-8:00) Mexico/BajaNorte (Pacific Standard Time)',
        'name' =>'America/Boise' => '(GMT-7:00) America/Boise (Mountain Standard Time)',
        'name' =>'America/Cambridge_Bay' => '(GMT-7:00) America/Cambridge_Bay (Mountain Standard Time)',
        'name' =>'America/Chihuahua' => '(GMT-7:00) America/Chihuahua (Mountain Standard Time)',
        'name' =>'America/Dawson_Creek' => '(GMT-7:00) America/Dawson_Creek (Mountain Standard Time)',
        'name' =>'America/Denver' => '(GMT-7:00) America/Denver (Mountain Standard Time)',
        'name' =>'America/Edmonton' => '(GMT-7:00) America/Edmonton (Mountain Standard Time)',
        'name' =>'America/Hermosillo' => '(GMT-7:00) America/Hermosillo (Mountain Standard Time)',
        'name' =>'America/Inuvik' => '(GMT-7:00) America/Inuvik (Mountain Standard Time)',
        'name' =>'America/Mazatlan' => '(GMT-7:00) America/Mazatlan (Mountain Standard Time)',
        'name' =>'America/Phoenix' => '(GMT-7:00) America/Phoenix (Mountain Standard Time)',
        'name' =>'America/Shiprock' => '(GMT-7:00) America/Shiprock (Mountain Standard Time)',
        'name' =>'America/Yellowknife' => '(GMT-7:00) America/Yellowknife (Mountain Standard Time)',
        'name' =>'Canada/Mountain' => '(GMT-7:00) Canada/Mountain (Mountain Standard Time)',
        'name' =>'Mexico/BajaSur' => '(GMT-7:00) Mexico/BajaSur (Mountain Standard Time)',
        'name' =>'America/Belize' => '(GMT-6:00) America/Belize (Central Standard Time)',
        'name' =>'America/Cancun' => '(GMT-6:00) America/Cancun (Central Standard Time)',
        'name' =>'America/Chicago' => '(GMT-6:00) America/Chicago (Central Standard Time)',
        'name' =>'America/Costa_Rica' => '(GMT-6:00) America/Costa_Rica (Central Standard Time)',
        'name' =>'America/El_Salvador' => '(GMT-6:00) America/El_Salvador (Central Standard Time)',
        'name' =>'America/Guatemala' => '(GMT-6:00) America/Guatemala (Central Standard Time)',
        'name' =>'America/Knox_IN' => '(GMT-6:00) America/Knox_IN (Central Standard Time)',
        'name' =>'America/Managua' => '(GMT-6:00) America/Managua (Central Standard Time)',
        'name' =>'America/Menominee' => '(GMT-6:00) America/Menominee (Central Standard Time)',
        'name' =>'America/Merida' => '(GMT-6:00) America/Merida (Central Standard Time)',
        'name' =>'America/Mexico_City' => '(GMT-6:00) America/Mexico_City (Central Standard Time)',
        'name' =>'America/Monterrey' => '(GMT-6:00) America/Monterrey (Central Standard Time)',
        'name' =>'America/Rainy_River' => '(GMT-6:00) America/Rainy_River (Central Standard Time)',
        'name' =>'America/Rankin_Inlet' => '(GMT-6:00) America/Rankin_Inlet (Central Standard Time)',
        'name' =>'America/Regina' => '(GMT-6:00) America/Regina (Central Standard Time)',
        'name' =>'America/Swift_Current' => '(GMT-6:00) America/Swift_Current (Central Standard Time)',
        'name' =>'America/Tegucigalpa' => '(GMT-6:00) America/Tegucigalpa (Central Standard Time)',
        'name' =>'America/Winnipeg' => '(GMT-6:00) America/Winnipeg (Central Standard Time)',
        'name' =>'Canada/Central' => '(GMT-6:00) Canada/Central (Central Standard Time)',
        'name' =>'Canada/East-Saskatchewan' => '(GMT-6:00) Canada/East-Saskatchewan (Central Standard Time)',
        'name' =>'Canada/Saskatchewan' => '(GMT-6:00) Canada/Saskatchewan (Central Standard Time)',
        'name' =>'Chile/EasterIsland' => '(GMT-6:00) Chile/EasterIsland (Easter Is. Time)',
        'name' =>'Mexico/General' => '(GMT-6:00) Mexico/General (Central Standard Time)',
        'name' =>'America/Atikokan' => '(GMT-5:00) America/Atikokan (Eastern Standard Time)',
        'name' =>'America/Bogota' => '(GMT-5:00) America/Bogota (Colombia Time)',
        'name' =>'America/Cayman' => '(GMT-5:00) America/Cayman (Eastern Standard Time)',
        'name' =>'America/Coral_Harbour' => '(GMT-5:00) America/Coral_Harbour (Eastern Standard Time)',
        'name' =>'America/Detroit' => '(GMT-5:00) America/Detroit (Eastern Standard Time)',
        'name' =>'America/Fort_Wayne' => '(GMT-5:00) America/Fort_Wayne (Eastern Standard Time)',
        'name' =>'America/Grand_Turk' => '(GMT-5:00) America/Grand_Turk (Eastern Standard Time)',
        'name' =>'America/Guayaquil' => '(GMT-5:00) America/Guayaquil (Ecuador Time)',
        'name' =>'America/Havana' => '(GMT-5:00) America/Havana (Cuba Standard Time)',
        'name' =>'America/Indianapolis' => '(GMT-5:00) America/Indianapolis (Eastern Standard Time)',
        'name' =>'America/Iqaluit' => '(GMT-5:00) America/Iqaluit (Eastern Standard Time)',
        'name' =>'America/Jamaica' => '(GMT-5:00) America/Jamaica (Eastern Standard Time)',
        'name' =>'America/Lima' => '(GMT-5:00) America/Lima (Peru Time)',
        'name' =>'America/Louisville' => '(GMT-5:00) America/Louisville (Eastern Standard Time)',
        'name' =>'America/Montreal' => '(GMT-5:00) America/Montreal (Eastern Standard Time)',
        'name' => 'America/Nassau' => '(GMT-5:00) America/Nassau (Eastern Standard Time)',
        'name' =>'America/New_York' => '(GMT-5:00) America/New_York (Eastern Standard Time)',
        'name' => 'America/Nipigon' => '(GMT-5:00) America/Nipigon (Eastern Standard Time)',
        'name' =>'America/Panama' => '(GMT-5:00) America/Panama (Eastern Standard Time)',
        'name' =>'America/Pangnirtung' => '(GMT-5:00) America/Pangnirtung (Eastern Standard Time)',
        'name' =>'America/Port-au-Prince' => '(GMT-5:00) America/Port-au-Prince (Eastern Standard Time)',
        'name' =>'America/Resolute' => '(GMT-5:00) America/Resolute (Eastern Standard Time)',
        'name' =>'America/Thunder_Bay' => '(GMT-5:00) America/Thunder_Bay (Eastern Standard Time)',
        'name' =>'America/Toronto' => '(GMT-5:00) America/Toronto (Eastern Standard Time)',
        'name' =>'Canada/Eastern' => '(GMT-5:00) Canada/Eastern (Eastern Standard Time)',
        'name' =>'America/Caracas' => '(GMT-4:-30) America/Caracas (Venezuela Time)',
        'name' =>'America/Anguilla' => '(GMT-4:00) America/Anguilla (Atlantic Standard Time)',
        'name' =>'America/Antigua' => '(GMT-4:00) America/Antigua (Atlantic Standard Time)',
        'name' =>'America/Aruba' => '(GMT-4:00) America/Aruba (Atlantic Standard Time)',
        'name' =>'America/Asuncion' => '(GMT-4:00) America/Asuncion (Paraguay Time)',
        'name' =>'America/Barbados' => '(GMT-4:00) America/Barbados (Atlantic Standard Time)',
        'name' =>'America/Blanc-Sablon' => '(GMT-4:00) America/Blanc-Sablon (Atlantic Standard Time)',
        'name' =>'America/Boa_Vista' => '(GMT-4:00) America/Boa_Vista (Amazon Time)',
        'name' =>'America/Campo_Grande' => '(GMT-4:00) America/Campo_Grande (Amazon Time)',
        'name' =>'America/Cuiaba' => '(GMT-4:00) America/Cuiaba (Amazon Time)',
        'name' =>'America/Curacao' => '(GMT-4:00) America/Curacao (Atlantic Standard Time)',
        'name' =>'America/Dominica' => '(GMT-4:00) America/Dominica (Atlantic Standard Time)',
        'name' =>'America/Eirunepe' => '(GMT-4:00) America/Eirunepe (Amazon Time)',
        'name' =>'America/Glace_Bay' => '(GMT-4:00) America/Glace_Bay (Atlantic Standard Time)',
        'name' =>'America/Goose_Bay' => '(GMT-4:00) America/Goose_Bay (Atlantic Standard Time)',
        'name' =>'America/Grenada' => '(GMT-4:00) America/Grenada (Atlantic Standard Time)',
        'America/Guadeloupe' => '(GMT-4:00) America/Guadeloupe (Atlantic Standard Time)',
        'America/Guyana' => '(GMT-4:00) America/Guyana (Guyana Time)',
        'America/Halifax' => '(GMT-4:00) America/Halifax (Atlantic Standard Time)',
        'America/La_Paz' => '(GMT-4:00) America/La_Paz (Bolivia Time)',
        'America/Manaus' => '(GMT-4:00) America/Manaus (Amazon Time)',
        'America/Marigot' => '(GMT-4:00) America/Marigot (Atlantic Standard Time)',
        'America/Martinique' => '(GMT-4:00) America/Martinique (Atlantic Standard Time)',
        'America/Moncton' => '(GMT-4:00) America/Moncton (Atlantic Standard Time)',
        'America/Montserrat' => '(GMT-4:00) America/Montserrat (Atlantic Standard Time)',
        'America/Port_of_Spain' => '(GMT-4:00) America/Port_of_Spain (Atlantic Standard Time)',
        'America/Porto_Acre' => '(GMT-4:00) America/Porto_Acre (Amazon Time)',
        'America/Porto_Velho' => '(GMT-4:00) America/Porto_Velho (Amazon Time)',
        'America/Puerto_Rico' => '(GMT-4:00) America/Puerto_Rico (Atlantic Standard Time)',
        'America/Rio_Branco' => '(GMT-4:00) America/Rio_Branco (Amazon Time)',
        'America/Santiago' => '(GMT-4:00) America/Santiago (Chile Time)',
        'America/Santo_Domingo' => '(GMT-4:00) America/Santo_Domingo (Atlantic Standard Time)',
        'America/St_Barthelemy' => '(GMT-4:00) America/St_Barthelemy (Atlantic Standard Time)',
        'America/St_Kitts' => '(GMT-4:00) America/St_Kitts (Atlantic Standard Time)',
        'America/St_Lucia' => '(GMT-4:00) America/St_Lucia (Atlantic Standard Time)',
        'America/St_Thomas' => '(GMT-4:00) America/St_Thomas (Atlantic Standard Time)',
        'America/St_Vincent' => '(GMT-4:00) America/St_Vincent (Atlantic Standard Time)',
        'America/Thule' => '(GMT-4:00) America/Thule (Atlantic Standard Time)',
        'America/Tortola' => '(GMT-4:00) America/Tortola (Atlantic Standard Time)',
        'America/Virgin' => '(GMT-4:00) America/Virgin (Atlantic Standard Time)',
        'Antarctica/Palmer' => '(GMT-4:00) Antarctica/Palmer (Chile Time)',
        'Atlantic/Bermuda' => '(GMT-4:00) Atlantic/Bermuda (Atlantic Standard Time)',
        'Atlantic/Stanley' => '(GMT-4:00) Atlantic/Stanley (Falkland Is. Time)',
        'Brazil/Acre' => '(GMT-4:00) Brazil/Acre (Amazon Time)',
        'Brazil/West' => '(GMT-4:00) Brazil/West (Amazon Time)',
        'Canada/Atlantic' => '(GMT-4:00) Canada/Atlantic (Atlantic Standard Time)',
        'Chile/Continental' => '(GMT-4:00) Chile/Continental (Chile Time)',
        'America/St_Johns' => '(GMT-3:-30) America/St_Johns (Newfoundland Standard Time)',
        'Canada/Newfoundland' => '(GMT-3:-30) Canada/Newfoundland (Newfoundland Standard Time)',
        'America/Araguaina' => '(GMT-3:00) America/Araguaina (Brasilia Time)',
        'America/Bahia' => '(GMT-3:00) America/Bahia (Brasilia Time)',
        'America/Belem' => '(GMT-3:00) America/Belem (Brasilia Time)',
        'America/Buenos_Aires' => '(GMT-3:00) America/Buenos_Aires (Argentine Time)',
        'America/Catamarca' => '(GMT-3:00) America/Catamarca (Argentine Time)',
        'America/Cayenne' => '(GMT-3:00) America/Cayenne (French Guiana Time)',
        'America/Cordoba' => '(GMT-3:00) America/Cordoba (Argentine Time)',
        'America/Fortaleza' => '(GMT-3:00) America/Fortaleza (Brasilia Time)',
        'America/Godthab' => '(GMT-3:00) America/Godthab (Western Greenland Time)',
        'America/Jujuy' => '(GMT-3:00) America/Jujuy (Argentine Time)',
        'America/Maceio' => '(GMT-3:00) America/Maceio (Brasilia Time)',
        'America/Mendoza' => '(GMT-3:00) America/Mendoza (Argentine Time)',
        'America/Miquelon' => '(GMT-3:00) America/Miquelon (Pierre & Miquelon Standard Time)',
        'America/Montevideo' => '(GMT-3:00) America/Montevideo (Uruguay Time)',
        'America/Paramaribo' => '(GMT-3:00) America/Paramaribo (Suriname Time)',
        'America/Recife' => '(GMT-3:00) America/Recife (Brasilia Time)',
        'America/Rosario' => '(GMT-3:00) America/Rosario (Argentine Time)',
        'America/Santarem' => '(GMT-3:00) America/Santarem (Brasilia Time)',
        'America/Sao_Paulo' => '(GMT-3:00) America/Sao_Paulo (Brasilia Time)',
        'Antarctica/Rothera' => '(GMT-3:00) Antarctica/Rothera (Rothera Time)',
        'Brazil/East' => '(GMT-3:00) Brazil/East (Brasilia Time)',
        'America/Noronha' => '(GMT-2:00) America/Noronha (Fernando de Noronha Time)',
        'Atlantic/South_Georgia' => '(GMT-2:00) Atlantic/South_Georgia (South Georgia Standard Time)',
        'Brazil/DeNoronha' => '(GMT-2:00) Brazil/DeNoronha (Fernando de Noronha Time)',
        'America/Scoresbysund' => '(GMT-1:00) America/Scoresbysund (Eastern Greenland Time)',
        'Atlantic/Azores' => '(GMT-1:00) Atlantic/Azores (Azores Time)',
        'Atlantic/Cape_Verde' => '(GMT-1:00) Atlantic/Cape_Verde (Cape Verde Time)',
        'Africa/Abidjan' => '(GMT+0:00) Africa/Abidjan (Greenwich Mean Time)',
        'Africa/Accra' => '(GMT+0:00) Africa/Accra (Ghana Mean Time)',
        'Africa/Bamako' => '(GMT+0:00) Africa/Bamako (Greenwich Mean Time)',
        'Africa/Banjul' => '(GMT+0:00) Africa/Banjul (Greenwich Mean Time)',
        'Africa/Bissau' => '(GMT+0:00) Africa/Bissau (Greenwich Mean Time)',
        'Africa/Casablanca' => '(GMT+0:00) Africa/Casablanca (Western European Time)',
        'Africa/Conakry' => '(GMT+0:00) Africa/Conakry (Greenwich Mean Time)',
        'Africa/Dakar' => '(GMT+0:00) Africa/Dakar (Greenwich Mean Time)',
        'Africa/El_Aaiun' => '(GMT+0:00) Africa/El_Aaiun (Western European Time)',
        'Africa/Freetown' => '(GMT+0:00) Africa/Freetown (Greenwich Mean Time)',
        'Africa/Lome' => '(GMT+0:00) Africa/Lome (Greenwich Mean Time)',
        'Africa/Monrovia' => '(GMT+0:00) Africa/Monrovia (Greenwich Mean Time)',
        'Africa/Nouakchott' => '(GMT+0:00) Africa/Nouakchott (Greenwich Mean Time)',
        'Africa/Ouagadougou' => '(GMT+0:00) Africa/Ouagadougou (Greenwich Mean Time)',
        'Africa/Sao_Tome' => '(GMT+0:00) Africa/Sao_Tome (Greenwich Mean Time)',
        'Africa/Timbuktu' => '(GMT+0:00) Africa/Timbuktu (Greenwich Mean Time)',
        'America/Danmarkshavn' => '(GMT+0:00) America/Danmarkshavn (Greenwich Mean Time)',
        'Atlantic/Canary' => '(GMT+0:00) Atlantic/Canary (Western European Time)',
        'Atlantic/Faeroe' => '(GMT+0:00) Atlantic/Faeroe (Western European Time)',
        'Atlantic/Faroe' => '(GMT+0:00) Atlantic/Faroe (Western European Time)',
        'Atlantic/Madeira' => '(GMT+0:00) Atlantic/Madeira (Western European Time)',
        'Atlantic/Reykjavik' => '(GMT+0:00) Atlantic/Reykjavik (Greenwich Mean Time)',
        'Atlantic/St_Helena' => '(GMT+0:00) Atlantic/St_Helena (Greenwich Mean Time)',
        'Europe/Belfast' => '(GMT+0:00) Europe/Belfast (Greenwich Mean Time)',
        'Europe/Dublin' => '(GMT+0:00) Europe/Dublin (Greenwich Mean Time)',
        'Europe/Guernsey' => '(GMT+0:00) Europe/Guernsey (Greenwich Mean Time)',
        'Europe/Isle_of_Man' => '(GMT+0:00) Europe/Isle_of_Man (Greenwich Mean Time)',
        'Europe/Jersey' => '(GMT+0:00) Europe/Jersey (Greenwich Mean Time)',
        'Europe/Lisbon' => '(GMT+0:00) Europe/Lisbon (Western European Time)',
        'Europe/London' => '(GMT+0:00) Europe/London (Greenwich Mean Time)',
        'Africa/Algiers' => '(GMT+1:00) Africa/Algiers (Central European Time)',
        'Africa/Bangui' => '(GMT+1:00) Africa/Bangui (Western African Time)',
        'Africa/Brazzaville' => '(GMT+1:00) Africa/Brazzaville (Western African Time)',
        'Africa/Ceuta' => '(GMT+1:00) Africa/Ceuta (Central European Time)',
        'Africa/Douala' => '(GMT+1:00) Africa/Douala (Western African Time)',
        'Africa/Kinshasa' => '(GMT+1:00) Africa/Kinshasa (Western African Time)',
        'Africa/Lagos' => '(GMT+1:00) Africa/Lagos (Western African Time)',
        'Africa/Libreville' => '(GMT+1:00) Africa/Libreville (Western African Time)',
        'Africa/Luanda' => '(GMT+1:00) Africa/Luanda (Western African Time)',
        'Africa/Malabo' => '(GMT+1:00) Africa/Malabo (Western African Time)',
        'Africa/Ndjamena' => '(GMT+1:00) Africa/Ndjamena (Western African Time)',
        'Africa/Niamey' => '(GMT+1:00) Africa/Niamey (Western African Time)',
        'Africa/Porto-Novo' => '(GMT+1:00) Africa/Porto-Novo (Western African Time)',
        'Africa/Tunis' => '(GMT+1:00) Africa/Tunis (Central European Time)',
        'Africa/Windhoek' => '(GMT+1:00) Africa/Windhoek (Western African Time)',
        'Arctic/Longyearbyen' => '(GMT+1:00) Arctic/Longyearbyen (Central European Time)',
        'Atlantic/Jan_Mayen' => '(GMT+1:00) Atlantic/Jan_Mayen (Central European Time)',
        'Europe/Amsterdam' => '(GMT+1:00) Europe/Amsterdam (Central European Time)',
        'Europe/Andorra' => '(GMT+1:00) Europe/Andorra (Central European Time)',
        'Europe/Belgrade' => '(GMT+1:00) Europe/Belgrade (Central European Time)',
        'Europe/Berlin' => '(GMT+1:00) Europe/Berlin (Central European Time)',
        'Europe/Bratislava' => '(GMT+1:00) Europe/Bratislava (Central European Time)',
        'Europe/Brussels' => '(GMT+1:00) Europe/Brussels (Central European Time)',
        'Europe/Budapest' => '(GMT+1:00) Europe/Budapest (Central European Time)',
        'Europe/Copenhagen' => '(GMT+1:00) Europe/Copenhagen (Central European Time)',
        'Europe/Gibraltar' => '(GMT+1:00) Europe/Gibraltar (Central European Time)',
        'Europe/Ljubljana' => '(GMT+1:00) Europe/Ljubljana (Central European Time)',
        'Europe/Luxembourg' => '(GMT+1:00) Europe/Luxembourg (Central European Time)',
        'Europe/Madrid' => '(GMT+1:00) Europe/Madrid (Central European Time)',
        'Europe/Malta' => '(GMT+1:00) Europe/Malta (Central European Time)',
        'Europe/Monaco' => '(GMT+1:00) Europe/Monaco (Central European Time)',
        'Europe/Oslo' => '(GMT+1:00) Europe/Oslo (Central European Time)',
        'Europe/Paris' => '(GMT+1:00) Europe/Paris (Central European Time)',
        'Europe/Podgorica' => '(GMT+1:00) Europe/Podgorica (Central European Time)',
        'Europe/Prague' => '(GMT+1:00) Europe/Prague (Central European Time)',
        'Europe/Rome' => '(GMT+1:00) Europe/Rome (Central European Time)',
        'Europe/San_Marino' => '(GMT+1:00) Europe/San_Marino (Central European Time)',
        'Europe/Sarajevo' => '(GMT+1:00) Europe/Sarajevo (Central European Time)',
        'Europe/Skopje' => '(GMT+1:00) Europe/Skopje (Central European Time)',
        'Europe/Stockholm' => '(GMT+1:00) Europe/Stockholm (Central European Time)',
        'Europe/Tirane' => '(GMT+1:00) Europe/Tirane (Central European Time)',
        'Europe/Vaduz' => '(GMT+1:00) Europe/Vaduz (Central European Time)',
        'Europe/Vatican' => '(GMT+1:00) Europe/Vatican (Central European Time)',
        'Europe/Vienna' => '(GMT+1:00) Europe/Vienna (Central European Time)',
        'Europe/Warsaw' => '(GMT+1:00) Europe/Warsaw (Central European Time)',
        'Europe/Zagreb' => '(GMT+1:00) Europe/Zagreb (Central European Time)',
        'Europe/Zurich' => '(GMT+1:00) Europe/Zurich (Central European Time)',
        'Africa/Blantyre' => '(GMT+2:00) Africa/Blantyre (Central African Time)',
        'Africa/Bujumbura' => '(GMT+2:00) Africa/Bujumbura (Central African Time)',
        'Africa/Cairo' => '(GMT+2:00) Africa/Cairo (Eastern European Time)',
        'Africa/Gaborone' => '(GMT+2:00) Africa/Gaborone (Central African Time)',
        'Africa/Harare' => '(GMT+2:00) Africa/Harare (Central African Time)',
        'Africa/Johannesburg' => '(GMT+2:00) Africa/Johannesburg (South Africa Standard Time)',
        'Africa/Kigali' => '(GMT+2:00) Africa/Kigali (Central African Time)',
        'Africa/Lubumbashi' => '(GMT+2:00) Africa/Lubumbashi (Central African Time)',
        'Africa/Lusaka' => '(GMT+2:00) Africa/Lusaka (Central African Time)',
        'Africa/Maputo' => '(GMT+2:00) Africa/Maputo (Central African Time)',
        'Africa/Maseru' => '(GMT+2:00) Africa/Maseru (South Africa Standard Time)',
        'Africa/Mbabane' => '(GMT+2:00) Africa/Mbabane (South Africa Standard Time)',
        'Africa/Tripoli' => '(GMT+2:00) Africa/Tripoli (Eastern European Time)',
        'Asia/Amman' => '(GMT+2:00) Asia/Amman (Eastern European Time)',
        'Asia/Beirut' => '(GMT+2:00) Asia/Beirut (Eastern European Time)',
        'Asia/Damascus' => '(GMT+2:00) Asia/Damascus (Eastern European Time)',
        'Asia/Gaza' => '(GMT+2:00) Asia/Gaza (Eastern European Time)',
        'Asia/Istanbul' => '(GMT+2:00) Asia/Istanbul (Eastern European Time)',
        'Asia/Jerusalem' => '(GMT+2:00) Asia/Jerusalem (Israel Standard Time)',
        'Asia/Nicosia' => '(GMT+2:00) Asia/Nicosia (Eastern European Time)',
        'Asia/Tel_Aviv' => '(GMT+2:00) Asia/Tel_Aviv (Israel Standard Time)',
        'Europe/Athens' => '(GMT+2:00) Europe/Athens (Eastern European Time)',
        'Europe/Bucharest' => '(GMT+2:00) Europe/Bucharest (Eastern European Time)',
        'Europe/Chisinau' => '(GMT+2:00) Europe/Chisinau (Eastern European Time)',
        'Europe/Helsinki' => '(GMT+2:00) Europe/Helsinki (Eastern European Time)',
        'Europe/Istanbul' => '(GMT+2:00) Europe/Istanbul (Eastern European Time)',
        'Europe/Kaliningrad' => '(GMT+2:00) Europe/Kaliningrad (Eastern European Time)',
        'Europe/Kiev' => '(GMT+2:00) Europe/Kiev (Eastern European Time)',
        'Europe/Mariehamn' => '(GMT+2:00) Europe/Mariehamn (Eastern European Time)',
        'Europe/Minsk' => '(GMT+2:00) Europe/Minsk (Eastern European Time)',
        'Europe/Nicosia' => '(GMT+2:00) Europe/Nicosia (Eastern European Time)',
        'Europe/Riga' => '(GMT+2:00) Europe/Riga (Eastern European Time)',
        'Europe/Simferopol' => '(GMT+2:00) Europe/Simferopol (Eastern European Time)',
        'Europe/Sofia' => '(GMT+2:00) Europe/Sofia (Eastern European Time)',
        'Europe/Tallinn' => '(GMT+2:00) Europe/Tallinn (Eastern European Time)',
        'Europe/Tiraspol' => '(GMT+2:00) Europe/Tiraspol (Eastern European Time)',
        'Europe/Uzhgorod' => '(GMT+2:00) Europe/Uzhgorod (Eastern European Time)',
        'Europe/Vilnius' => '(GMT+2:00) Europe/Vilnius (Eastern European Time)',
        'Europe/Zaporozhye' => '(GMT+2:00) Europe/Zaporozhye (Eastern European Time)',
        'Africa/Addis_Ababa' => '(GMT+3:00) Africa/Addis_Ababa (Eastern African Time)',
        'Africa/Asmara' => '(GMT+3:00) Africa/Asmara (Eastern African Time)',
        'Africa/Asmera' => '(GMT+3:00) Africa/Asmera (Eastern African Time)',
        'Africa/Dar_es_Salaam' => '(GMT+3:00) Africa/Dar_es_Salaam (Eastern African Time)',
        'Africa/Djibouti' => '(GMT+3:00) Africa/Djibouti (Eastern African Time)',
        'Africa/Kampala' => '(GMT+3:00) Africa/Kampala (Eastern African Time)',
        'Africa/Khartoum' => '(GMT+3:00) Africa/Khartoum (Eastern African Time)',
        'Africa/Mogadishu' => '(GMT+3:00) Africa/Mogadishu (Eastern African Time)',
        'Africa/Nairobi' => '(GMT+3:00) Africa/Nairobi (Eastern African Time)',
        'Antarctica/Syowa' => '(GMT+3:00) Antarctica/Syowa (Syowa Time)',
        'Asia/Aden' => '(GMT+3:00) Asia/Aden (Arabia Standard Time)',
        'Asia/Baghdad' => '(GMT+3:00) Asia/Baghdad (Arabia Standard Time)',
        'Asia/Bahrain' => '(GMT+3:00) Asia/Bahrain (Arabia Standard Time)',
        'Asia/Kuwait' => '(GMT+3:00) Asia/Kuwait (Arabia Standard Time)',
        'Asia/Qatar' => '(GMT+3:00) Asia/Qatar (Arabia Standard Time)',
        'Europe/Moscow' => '(GMT+3:00) Europe/Moscow (Moscow Standard Time)',
        'Europe/Volgograd' => '(GMT+3:00) Europe/Volgograd (Volgograd Time)',
        'Indian/Antananarivo' => '(GMT+3:00) Indian/Antananarivo (Eastern African Time)',
        'Indian/Comoro' => '(GMT+3:00) Indian/Comoro (Eastern African Time)',
        'Indian/Mayotte' => '(GMT+3:00) Indian/Mayotte (Eastern African Time)',
        'Asia/Tehran' => '(GMT+3:30) Asia/Tehran (Iran Standard Time)',
        'Asia/Baku' => '(GMT+4:00) Asia/Baku (Azerbaijan Time)',
        'Asia/Dubai' => '(GMT+4:00) Asia/Dubai (Gulf Standard Time)',
        'Asia/Muscat' => '(GMT+4:00) Asia/Muscat (Gulf Standard Time)',
        'Asia/Tbilisi' => '(GMT+4:00) Asia/Tbilisi (Georgia Time)',
        'Asia/Yerevan' => '(GMT+4:00) Asia/Yerevan (Armenia Time)',
        'Europe/Samara' => '(GMT+4:00) Europe/Samara (Samara Time)',
        'Indian/Mahe' => '(GMT+4:00) Indian/Mahe (Seychelles Time)',
        'Indian/Mauritius' => '(GMT+4:00) Indian/Mauritius (Mauritius Time)',
        'Indian/Reunion' => '(GMT+4:00) Indian/Reunion (Reunion Time)',
        'Asia/Kabul' => '(GMT+4:30) Asia/Kabul (Afghanistan Time)',
        'Asia/Aqtau' => '(GMT+5:00) Asia/Aqtau (Aqtau Time)',
        'Asia/Aqtobe' => '(GMT+5:00) Asia/Aqtobe (Aqtobe Time)',
        'Asia/Ashgabat' => '(GMT+5:00) Asia/Ashgabat (Turkmenistan Time)',
        'Asia/Ashkhabad' => '(GMT+5:00) Asia/Ashkhabad (Turkmenistan Time)',
        'Asia/Dushanbe' => '(GMT+5:00) Asia/Dushanbe (Tajikistan Time)',
        'Asia/Karachi' => '(GMT+5:00) Asia/Karachi (Pakistan Time)',
        'Asia/Oral' => '(GMT+5:00) Asia/Oral (Oral Time)',
        'Asia/Samarkand' => '(GMT+5:00) Asia/Samarkand (Uzbekistan Time)',
        'Asia/Tashkent' => '(GMT+5:00) Asia/Tashkent (Uzbekistan Time)',
        'Asia/Yekaterinburg' => '(GMT+5:00) Asia/Yekaterinburg (Yekaterinburg Time)',
        'Indian/Kerguelen' => '(GMT+5:00) Indian/Kerguelen (French Southern & Antarctic Lands Time)',
        'Indian/Maldives' => '(GMT+5:00) Indian/Maldives (Maldives Time)',
        'Asia/Calcutta' => '(GMT+5:30) Asia/Calcutta (India Standard Time)',
        'Asia/Colombo' => '(GMT+5:30) Asia/Colombo (India Standard Time)',
        'Asia/Kolkata' => '(GMT+5:30) Asia/Kolkata (India Standard Time)',
        'Asia/Katmandu' => '(GMT+5:45) Asia/Katmandu (Nepal Time)',
        'Antarctica/Mawson' => '(GMT+6:00) Antarctica/Mawson (Mawson Time)',
        'Antarctica/Vostok' => '(GMT+6:00) Antarctica/Vostok (Vostok Time)',
        'Asia/Almaty' => '(GMT+6:00) Asia/Almaty (Alma-Ata Time)',
        'Asia/Bishkek' => '(GMT+6:00) Asia/Bishkek (Kirgizstan Time)',
        'Asia/Dacca' => '(GMT+6:00) Asia/Dacca (Bangladesh Time)',
        'Asia/Dhaka' => '(GMT+6:00) Asia/Dhaka (Bangladesh Time)',
        'Asia/Novosibirsk' => '(GMT+6:00) Asia/Novosibirsk (Novosibirsk Time)',
        'Asia/Omsk' => '(GMT+6:00) Asia/Omsk (Omsk Time)',
        'Asia/Qyzylorda' => '(GMT+6:00) Asia/Qyzylorda (Qyzylorda Time)',
        'Asia/Thimbu' => '(GMT+6:00) Asia/Thimbu (Bhutan Time)',
        'Asia/Thimphu' => '(GMT+6:00) Asia/Thimphu (Bhutan Time)',
        'Indian/Chagos' => '(GMT+6:00) Indian/Chagos (Indian Ocean Territory Time)',
        'Asia/Rangoon' => '(GMT+6:30) Asia/Rangoon (Myanmar Time)',
        'Indian/Cocos' => '(GMT+6:30) Indian/Cocos (Cocos Islands Time)',
        'Antarctica/Davis' => '(GMT+7:00) Antarctica/Davis (Davis Time)',
        'Asia/Bangkok' => '(GMT+7:00) Asia/Bangkok (Indochina Time)',
        'Asia/Ho_Chi_Minh' => '(GMT+7:00) Asia/Ho_Chi_Minh (Indochina Time)',
        'Asia/Hovd' => '(GMT+7:00) Asia/Hovd (Hovd Time)',
        'Asia/Jakarta' => '(GMT+7:00) Asia/Jakarta (West Indonesia Time)',
        'Asia/Krasnoyarsk' => '(GMT+7:00) Asia/Krasnoyarsk (Krasnoyarsk Time)',
        'Asia/Phnom_Penh' => '(GMT+7:00) Asia/Phnom_Penh (Indochina Time)',
        'Asia/Pontianak' => '(GMT+7:00) Asia/Pontianak (West Indonesia Time)',
        'Asia/Saigon' => '(GMT+7:00) Asia/Saigon (Indochina Time)',
        'Asia/Vientiane' => '(GMT+7:00) Asia/Vientiane (Indochina Time)',
        'Indian/Christmas' => '(GMT+7:00) Indian/Christmas (Christmas Island Time)',
        'Antarctica/Casey' => '(GMT+8:00) Antarctica/Casey (Western Standard Time (Australia))',
        'Asia/Brunei' => '(GMT+8:00) Asia/Brunei (Brunei Time)',
        'Asia/Choibalsan' => '(GMT+8:00) Asia/Choibalsan (Choibalsan Time)',
        'Asia/Chongqing' => '(GMT+8:00) Asia/Chongqing (China Standard Time)',
        'Asia/Chungking' => '(GMT+8:00) Asia/Chungking (China Standard Time)',
        'Asia/Harbin' => '(GMT+8:00) Asia/Harbin (China Standard Time)',
        'Asia/Hong_Kong' => '(GMT+8:00) Asia/Hong_Kong (Hong Kong Time)',
        'Asia/Irkutsk' => '(GMT+8:00) Asia/Irkutsk (Irkutsk Time)',
        'Asia/Kashgar' => '(GMT+8:00) Asia/Kashgar (China Standard Time)',
        'Asia/Kuala_Lumpur' => '(GMT+8:00) Asia/Kuala_Lumpur (Malaysia Time)',
        'Asia/Kuching' => '(GMT+8:00) Asia/Kuching (Malaysia Time)',
        'Asia/Macao' => '(GMT+8:00) Asia/Macao (China Standard Time)',
        'Asia/Macau' => '(GMT+8:00) Asia/Macau (China Standard Time)',
        'Asia/Makassar' => '(GMT+8:00) Asia/Makassar (Central Indonesia Time)',
        'Asia/Manila' => '(GMT+8:00) Asia/Manila (Philippines Time)',
        'Asia/Shanghai' => '(GMT+8:00) Asia/Shanghai (China Standard Time)',
        'Asia/Singapore' => '(GMT+8:00) Asia/Singapore (Singapore Time)',
        'Asia/Taipei' => '(GMT+8:00) Asia/Taipei (China Standard Time)',
        'Asia/Ujung_Pandang' => '(GMT+8:00) Asia/Ujung_Pandang (Central Indonesia Time)',
        'Asia/Ulaanbaatar' => '(GMT+8:00) Asia/Ulaanbaatar (Ulaanbaatar Time)',
        'Asia/Ulan_Bator' => '(GMT+8:00) Asia/Ulan_Bator (Ulaanbaatar Time)',
        'Asia/Urumqi' => '(GMT+8:00) Asia/Urumqi (China Standard Time)',
        'Australia/Perth' => '(GMT+8:00) Australia/Perth (Western Standard Time (Australia))',
        'Australia/West' => '(GMT+8:00) Australia/West (Western Standard Time (Australia))',
        'Australia/Eucla' => '(GMT+8:45) Australia/Eucla (Central Western Standard Time (Australia))',
        'Asia/Dili' => '(GMT+9:00) Asia/Dili (Timor-Leste Time)',
        'Asia/Jayapura' => '(GMT+9:00) Asia/Jayapura (East Indonesia Time)',
        'Asia/Pyongyang' => '(GMT+9:00) Asia/Pyongyang (Korea Standard Time)',
        'Asia/Seoul' => '(GMT+9:00) Asia/Seoul (Korea Standard Time)',
        'Asia/Tokyo' => '(GMT+9:00) Asia/Tokyo (Japan Standard Time)',
        'Asia/Yakutsk' => '(GMT+9:00) Asia/Yakutsk (Yakutsk Time)',
        'Australia/Adelaide' => '(GMT+9:30) Australia/Adelaide (Central Standard Time (South Australia))',
        'Australia/Broken_Hill' => '(GMT+9:30) Australia/Broken_Hill (Central Standard Time (South Australia/New South Wales))',
        'Australia/Darwin' => '(GMT+9:30) Australia/Darwin (Central Standard Time (Northern Territory))',
        'Australia/North' => '(GMT+9:30) Australia/North (Central Standard Time (Northern Territory))',
        'Australia/South' => '(GMT+9:30) Australia/South (Central Standard Time (South Australia))',
        'Australia/Yancowinna' => '(GMT+9:30) Australia/Yancowinna (Central Standard Time (South Australia/New South Wales))',
        'Antarctica/DumontDUrville' => '(GMT+10:00) Antarctica/DumontDUrville (Dumont-d\'Urville Time)',
        'Asia/Sakhalin' => '(GMT+10:00) Asia/Sakhalin (Sakhalin Time)',
        'Asia/Vladivostok' => '(GMT+10:00) Asia/Vladivostok (Vladivostok Time)',
        'Australia/ACT' => '(GMT+10:00) Australia/ACT (Eastern Standard Time (New South Wales))',
        'Australia/Brisbane' => '(GMT+10:00) Australia/Brisbane (Eastern Standard Time (Queensland))',
        'Australia/Canberra' => '(GMT+10:00) Australia/Canberra (Eastern Standard Time (New South Wales))',
        'Australia/Currie' => '(GMT+10:00) Australia/Currie (Eastern Standard Time (New South Wales))',
        'Australia/Hobart' => '(GMT+10:00) Australia/Hobart (Eastern Standard Time (Tasmania))',
        'Australia/Lindeman' => '(GMT+10:00) Australia/Lindeman (Eastern Standard Time (Queensland))',
        'Australia/Melbourne' => '(GMT+10:00) Australia/Melbourne (Eastern Standard Time (Victoria))',
        'Australia/NSW' => '(GMT+10:00) Australia/NSW (Eastern Standard Time (New South Wales))',
        'Australia/Queensland' => '(GMT+10:00) Australia/Queensland (Eastern Standard Time (Queensland))',
        'Australia/Sydney' => '(GMT+10:00) Australia/Sydney (Eastern Standard Time (New South Wales))',
        'Australia/Tasmania' => '(GMT+10:00) Australia/Tasmania (Eastern Standard Time (Tasmania))',
        'Australia/Victoria' => '(GMT+10:00) Australia/Victoria (Eastern Standard Time (Victoria))',
        'Australia/LHI' => '(GMT+10:30) Australia/LHI (Lord Howe Standard Time)',
        'Australia/Lord_Howe' => '(GMT+10:30) Australia/Lord_Howe (Lord Howe Standard Time)',
        'Asia/Magadan' => '(GMT+11:00) Asia/Magadan (Magadan Time)',
        'Antarctica/McMurdo' => '(GMT+12:00) Antarctica/McMurdo (New Zealand Standard Time)',
        'Antarctica/South_Pole' => '(GMT+12:00) Antarctica/South_Pole (New Zealand Standard Time)',
        'Asia/Anadyr' => '(GMT+12:00) Asia/Anadyr (Anadyr Time)',
        'Asia/Kamchatka' => '(GMT+12:00) Asia/Kamchatka (Petropavlovsk-Kamchatski Time)'
    ];
}
